## 다중회귀모델(Multiple Regression Model)
##### - 여러 개의 특성(독립변수 = 항목 = 칼럼 = 변수 = 퓨처)을 사용한 선형회귀
##### - 특성이 많을 수록, 복잡도가 높아 집니다.
##### - 1개의 특성으로는 선형회귀모델이 '직선'을 학습한다면,
##### - 2개이상의 특성으로는 선형회귀모델이 "평면"을 학습하게 됩니다.
#####
## 다중회귀모델 공식(방정식) - feature =  columns
##### y = a * 특성1 + b * 특성2 + c * 특성3.......+y절편

##### 데이터 준비하기
##### 구글드라이브 > dataset > 머신러닝 > data > 03_농어...csv

## <사용할 데이터>
##### -훈련데이터(독립변수) : 길이(length), 높이(height) , 두께(width)
##### -target데이터(종속변수) : 무게
##### -새로 추가할 데이터 : (길이 + 높이)= 면적
##### -모든 작업은 사이킷런에서 제공하는 함수 이용

## 특성공학
##### - 기존의 특성을 이용해서 " 새로운 특성(항목)"을 만들어내는 작업

In [7]:
### 데이터프레임을 2차원으로 바꾸기 ..
# 데이터프레임은 2차원 ..
# to_numpy()
perch_full = df.to_numpy()
perch_full

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94],
       [18.  ,  5.22,  3.32],
       [18.7 ,  5.2 ,  3.12],
       [19.  ,  5.64,  3.05],
       [19.6 ,  5.14,  3.04],
       [20.  ,  5.08,  2.77],
       [21.  ,  5.69,  3.56],
       [21.  ,  5.92,  3.31],
       [21.  ,  5.69,  3.67],
       [21.3 ,  6.38,  3.53],
       [22.  ,  6.11,  3.41],
       [22.  ,  5.64,  3.52],
       [22.  ,  6.11,  3.52],
       [22.  ,  5.88,  3.52],
       [22.  ,  5.52,  4.  ],
       [22.5 ,  5.86,  3.62],
       [22.5 ,  6.79,  3.62],
       [22.7 ,  5.95,  3.63],
       [23.  ,  5.22,  3.63],
       [23.5 ,  6.28,  3.72],
       [24.  ,  7.29,  3.72],
       [24.  ,  6.38,  3.82],
       [24.6 ,  6.73,  4.17],
       [25.  ,  6.44,  3.68],
       [25.6 ,  6.56,  4.24],
       [26.5 ,  7.17,  4.14],
       [27.3 ,  8.32,  5.14],
       [27.5 ,  7.17,  4.34],
       [27.5 ,  7.05,  4.34],
       [27

In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv('./03_농어의_길이_높이_두께_데이터.csv',encoding = 'utf-8-sig')
df.head()

length   height   width
0     8.4     2.11    1.41
1    13.7     3.53    2.00
2    15.0     3.82    2.43
3    16.2     4.59    2.63
4    17.4     4.59    2.94

In [12]:
perch_weight = np.array(
    [5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 
     110.0, 115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 
     130.0, 150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 
     197.0, 218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 
     514.0, 556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 
     820.0, 850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 
     1000.0, 1000.0]
     )
perch_weight

array([   5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
        685. ,  700. ,  700. ,  690. ,  900. ,  650. ,  820. ,  850. ,
        900. , 1015. ,  820. , 1100. , 1000. , 1100. , 1000. , 1000. ])

In [26]:
### 1. 훈련데이터와 테스트데이터 분리하기
from sklearn.model_selection import train_test_split

## 훈련데이터 / 테스트데이터 세트 생성하기
train_input, test_input, train_target,  test_target = train_test_split(df,perch_weight, test_size = 0.25, random_state = 42)

In [28]:
print(train_input.shape)
print(test_input.shape)
print(train_target.shape)
print(test_target.shape)

(42, 3)
(14, 3)
(42,)
(14,)


In [29]:
### 사이킷런 변환기 클래스
from sklearn.preprocessing import PolynomialFeatures

In [40]:
### 객체생성(모델)
poly = PolynomialFeatures(include_bias = False)

### 임의값 사용
temp_data = [[2,3]]

## 훈련시키기 :: 새롭게 만들 스스로 특성 조합 찾기
poly.fit(temp_data)

### 찾은 특성 조합으로 데이터 변환하기
print(poly.transform(temp_data))

###<변환기 특성 조합 생성 규칙>
# - 첫번째 나온 1의값 : y절편 값 (무조건 첨에 1이 나옵니다.)
# - 두번째-세번째 : 자기 자신의 값을 그대로 넣습니다.
# - 네번째 : 2의 값을 제곱
# - 다섯번째 : 2 * 3
# - 여섯번째 : 3의 제곱


### y절편 1의 값은 PolynomialFeatures 클래스에서 기본적으로
# 특성에 추가된 절편값을 무시해 버립니다.
# - 추가된 y절편 1은 무시해도 되는 값입니다.
# 보통 PolynomialFeatures 클래스 생성시에 제외시키는 속성을 사용합니다.
# - include_bias = False 옵션 사용하면 y절편값 제외 시킵니다.

[[2. 3. 4. 6. 9.]]


## 특성 만들기 : 사이킷런의 변환기
#### -사이킷런은 특성을 만들거나 전처리하기 위한 다양한 객체를 제공
#### -사이킷런에서 제공하는 이런 클래스들을 "변환기"라고 부릅니다
## <특성 생성 패키지>
##### - 사용되는 패키지 : sklearn.preprocessing
##### - 사용되는 클래스 : PolynomialFeatures
##### - 사용되는 함수 : fit(), transform(), fit_transforms()
##### - 특성 생성 시 사용하는 데이터는 train_input, test_input 2개
##### - 훈련에 영향을 미치는 특성(항목)을 스스로 찾아서 생성하는 것이 목적이기 때문에
##### - ...target데이터는 해당사항이 없습니다 (정답은 변경되면 안됩니다)

In [59]:
### train_input, test_input 데이터 변환하기...
# 변수명 : train_poly, test_poly 사용
poly.fit(train_input)
train_poly = poly.transform(train_input)
print(train_poly.shape)

(42, 9)


In [60]:
test_poly = poly.transform(test_input)
print(test_poly.shape)

(14, 9)


In [58]:
train_input

length   height   width
8     19.6     5.14    3.04
17    22.0     5.88    3.52
6     18.7     5.20    3.12
4     17.4     4.59    2.94
41    36.0    10.61    6.74
27    25.0     6.44    3.68
47    40.0    11.93    7.11
46    39.0    12.43    7.35
52    43.0    11.93    7.28
15    22.0     5.64    3.52
9     20.0     5.08    2.77
16    22.0     6.11    3.52
24    24.0     7.29    3.72
31    27.5     7.17    4.34
53    43.0    12.51    7.42
48    40.0    11.73    7.22
25    24.0     6.38    3.82
11    21.0     5.92    3.31
32    27.5     7.05    4.34
49    40.0    12.38    7.46
37    32.8    10.03    6.02
29    26.5     7.17    4.14
40    36.5    10.88    6.86
1     13.7     3.53    2.00
21    22.7     5.95    3.63
2     15.0     3.82    2.43
43    37.0    10.57    6.37
39    35.0    11.49    7.80
35    28.7     7.59    4.64
23    23.5     6.28    3.72
45    39.0    11.14    6.00
10    21.0     5.69    3.56
22    23.0     5.22    3.63
18    22.0     5.52    4.00
55    44.0    12.49    7.60
20    22.5     6.79    3.62
7     19.0     5.64    3.05
42    37.0    10.84    6.26
14    22.0     6.11    3.41
28    25.6     6.56    4.24
51    42.0    12.80    6.87
38    34.5    10.26    6.39

In [61]:
### 강사님 풀이
### 특성항목 조합패턴 : 기본적인 조합은 2차원을 사용합니다
# degree = 2

### train_input, test_input 데이터 변환하기 ...
## 객체생성(모델)
poly = PolynomialFeatures(include_bias = False)

### 훈련시키기 : 새롭게 만들 스스로 특성 조합 찾기
poly.fit(train_input)

### 찾은 특성 조합으로 데이터 변환하기
# - 훈련데이터 변환하기
train_poly = poly.transform(train_input)

# - 테스트데이터 변환하기
test_poly = poly.transform(test_input)

print(train_poly.shape , test_poly.shape)


(42, 9) (14, 9)


In [64]:
### 훈련모델이 사용된 조합의 패턴을 가지고 있습니다
poly.get_feature_names_out()

array(['length', ' height', ' width', 'length^2', 'length  height',
       'length  width', ' height^2', ' height  width', ' width^2'],
      dtype=object)

In [65]:
poly.get_feature_names()

['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2', 'x2^2']